### ISSUE TITLE
JWT authentication feature for this repository

### ISSUE THREAD

**Issue by GouravRusiya30** [GouravRusiya30/SpringBootRestAPI#3]

**Comment by manojshankar** [comment]
I have experience in implement JWT authentication, want to know what are you trying to achieve. Can you elaborated about the issue?

Thank you.

**Comment by GouravRusiya30** [comment]
Hello @manojshankar 
Thanks for showing interest in this feature request.

Currently if you check [PetsController](https://github.com/GouravRusiya30/SpringBootRestAPI/blob/master/src/main/java/com/gourav/restapi/controllers/PetsController.java) it's not secure & doesn't needs any authentication while Create/Delete/Modify operations. It will be good to have JWT auth feature for this API.

Let me know if you are interested to work on this.

**Comment by manojshankar** [comment]
Understood I add the JWT Authentication framework feature.

**Comment by GouravRusiya30** [comment]
@manojshankar are you working on this?
Contact me to discuss further - gouravrusiya.lnct@gmail.com

**Comment by goyal27** [comment]
@GouravRusiya30 can I pick this up?

**Comment by GouravRusiya30** [comment]
@goyal27 Sure, go ahead but please read the [Contributing Guide](https://github.com/GouravRusiya30/SpringBootRestAPI/blob/master/CONTRIBUTING.md) and [PR template](https://github.com/GouravRusiya30/SpringBootRestAPI/blob/master/PULL_REQUEST_TEMPLATE)

Also, first try to setup locally and see if it is working then raise a PR

**Comment by goyal27** [comment]
@GouravRusiya30 I went through the README but couldn't find the objective of this project if you can help that would be a great motivation for me to contribute.

**Comment by GouravRusiya30** [comment]
@goyal27 Can you drop me an email - gouravrusiya.lnct@gmail.com
We can discuss further.

**Comment by GouravRusiya30** [comment]
The main objective behind is to make this repo as a Template for Rest API using spring-boot-microservices and MongoDB with proper JWT auth which will be helpful for others to use this as a framework on to Kickstart easily.

**Comment by ravening** [comment]
is this already picked up or need help on this? I have a similar project on spring boot/mongo wiht jwt

**Comment by GouravRusiya30** [comment]
Hey @ravening I haven't heard back from @goyal27 
So you can pick this issue. Go ahead.
Let me know if you need any further information on this.

**Comment by GouravRusiya30** [comment]
Thanks @ravening  for your Contribution !!!
